# Generated by Django 5.1 on 2024-09-30 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='enter valid mobile number', regex='^[6-9]\\d{9}$')])),
            ],
        ),
    ]
