# Generated by Django 5.1.1 on 2024-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='not-provided@gmail.com', max_length=254),
        ),
    ]
